feat: sns-sqs-integration
selfdecode/events-library pull request #10
Opened 2021-08-18 06:55 UTC by waseem-uddin

2021-08-24 06:41 UTC, diraven requested changes

2021-08-24 06:41 UTC, diraven commented on events_library/core/event_bus_sns.py
> +    def emit_cud_locally(cls, cud_event_name: str, payload: Dict) -> None:
It's often a good idea to prefix methods and attributes that would be considered "protected" or "private" in other languages with underscores in python.

2021-08-24 06:41 UTC, diraven commented on events_library/core/event_bus_sns.py
> +    map_event_to_handlers: Dict[str, List[Callable]] = {}
map_event_to_handlers and map_event_to_target_services right next to each other in the same class make it feel like they are a part of the same interaction level, while one is for local interactions and the other one is for remote interactions. And they do not have anything in common.

It may make sense to have something like event_to_loval_handlers and event_to_remote_services or something similar to outline.

Ideally, it may even make sense to split event receiver class from event sender class, which will be much more explicit and easy to understand.

Same concern is about cud events below, although to a slightly lesser extent.

2021-08-24 06:41 UTC, diraven commented on events_library/core/event_bus_sns.py
> +    def get_s3_file_content(cls, s3_client, payload: Dict) -> List[dict]:
This will essentially have to be implemented in streaming format e.g. csv. The bigger our tables become - the more apparent RAM and time limits will be.

2021-08-24 06:41 UTC, diraven commented on events_library/core/event_bus_sns.py
> +    def start_polling(cls):
May make sense to be a part of sd v1 code base directly. It's not used anywhere else, so no need for it to be in the library. Also v1 is unmaintained and may give us dependency conflicts which we probably don't want to deal with.

2021-08-24 06:41 UTC, diraven commented on events_library/domain/constants.py
> +    EMAILS = "emails"
Another new service is "search", may want to add that one took.

2021-08-24 06:41 UTC, diraven commented on events_library/management/commands/event_handler.py
> +                if sync_task_serializer.is_valid():
We should either raise some exception if sync task is not valid or not validate at all. Otherwise we'll be dropping events silently which is not ideal.

2021-08-24 06:41 UTC, diraven commented on events_library/management/commands/sync_cud_model.py
> +                    logger.error(f"An error occurred while notifying target_service: {send_event_summary['error_message']}")
We should use logger everywhere instead of print() statements, unless those print()'s are for debugging purposes.

2021-08-24 06:41 UTC, diraven commented on events_library/tasks.py
> +from os import name
Same thing, should probably go into v1 source code directly.

2021-08-24 06:41 UTC, diraven commented on setup.py
> +        "celery[redis]==3.*",
Same thing, should go to v1 code base. We don't really need this installed in all of our django-based microservices.

2021-08-24 06:41 UTC, diraven commented on events_library/utils.py
> +    - 'emails'
Also "search".

2021-08-24 07:11 UTC, waseem-uddin commented on events_library/core/event_bus_sns.py
> +    def get_s3_file_content(cls, s3_client, payload: Dict) -> List[dict]:
I am not entirely sure how the data format thing works. Does this mean we need to make some change [here](https://github.com/selfdecode/events-library/blob/f0f2002485c36deeec8204f25964b93bdbf207cd/events_library/management/commands/sync_cud_model.py#L69) too?

2021-08-24 07:13 UTC, waseem-uddin commented on events_library/core/event_bus_sns.py
> +    def start_polling(cls):
Any suggestion where we could place it? How about directly in the tasks.py file [here](https://bitbucket.org/selfdecode/sd-selfdecode/src/bfa683ff0f18c6cc286a5ad30bc8d6097dc8bff0/app/decodify/tasks.py?at=feature%2Fsns-sqs-integration#lines-32)?

2021-08-24 07:13 UTC, diraven commented
Yes. It's not a small task and is not urgent. Something to implement later.
Right now it is out of scope.

вт, 24 серп. 2021, 10:11 користувач Syed Waseem Ud Din <
***@***.***> пише:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In events_library/core/event_bus_sns.py
> <https://github.com/selfdecode/events-library/pull/10#discussion_r694564070>
> :
>
> > +        except Exception as error:
> +            error_message = f"An error occurred while synchronizing the data: {error}"
> +            cls.store_sync_task_exception_locally(sync_task_instance, error_message)
> +            raise
> +
> +        try:
> +            cls.delete_s3_file(s3_client, payload)
> +            sync_task_instance.was_processed = True
> +            sync_task_instance.save()
> +        except ClientError as error:
> +            error_message = f"An error occurred while deleting the file in S3: {error}"
> +            cls.store_sync_task_exception_locally(sync_task_instance, error_message)
> +            raise
> +
> +    @classmethod
> +    def get_s3_file_content(cls, s3_client, payload: Dict) -> List[dict]:
>
> I am not entirely sure how the data format thing works. Does this mean we
> need to make some change here
> <https://github.com/selfdecode/events-library/blob/f0f2002485c36deeec8204f25964b93bdbf207cd/events_library/management/commands/sync_cud_model.py#L69>
> too?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/selfdecode/events-library/pull/10#discussion_r694564070>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2N54TOMK6HVLJHJFASW3T6NAZLANCNFSM5CLL24EQ>
> .
>

2021-08-24 07:20 UTC, waseem-uddin commented on events_library/management/commands/sync_cud_model.py
> +                    logger.error(f"An error occurred while notifying target_service: {send_event_summary['error_message']}")
Agreed. I have kept them in place only for testing purposes. I will remove it from all the places (along with TODOs and commented code) once we successfully test it out on cloud.

2021-08-24 09:38 UTC, waseem-uddin commented on events_library/core/event_api_sns.py
> +    """Class for making HTTP request related to events"""
Done

2021-08-24 09:38 UTC, waseem-uddin commented on events_library/core/event_api_sns.py
> +                    Tells if the event was received and handled
Done

2021-08-24 09:38 UTC, waseem-uddin commented on events_library/core/event_api_sns.py
> +                retry_number: int
Done

2021-08-24 09:39 UTC, waseem-uddin commented on events_library/core/event_bus_sns.py
> +    def start_polling(cls):
Done

2021-08-24 09:39 UTC, waseem-uddin commented on events_library/domain/constants.py
> +    EMAILS = "emails"
Done

2021-08-24 09:39 UTC, waseem-uddin commented on events_library/management/commands/event_handler.py
> +                if sync_task_serializer.is_valid():
Done

2021-08-24 09:39 UTC, waseem-uddin commented on events_library/tasks.py
> +from os import name
Done

2021-08-24 09:39 UTC, waseem-uddin commented on setup.py
> +        "celery[redis]==3.*",
Done

2021-08-24 09:39 UTC, waseem-uddin commented on events_library/utils.py
> +    - 'emails'
Done

2021-08-24 09:40 UTC, waseem-uddin commented on events_library/core/event_bus_sns.py
> +    def emit_cud_locally(cls, cud_event_name: str, payload: Dict) -> None:
It will be handled in https://github.com/selfdecode/devops/issues/242

2021-08-24 09:40 UTC, waseem-uddin commented on events_library/core/event_bus_sns.py
> +    map_event_to_handlers: Dict[str, List[Callable]] = {}
It will be handled in https://github.com/selfdecode/devops/issues/242

2021-08-24 09:41 UTC, waseem-uddin commented on events_library/core/event_bus_sns.py
> +    def get_s3_file_content(cls, s3_client, payload: Dict) -> List[dict]:
It will be handled in https://github.com/selfdecode/devops/issues/252

2021-08-24 15:54 UTC, diraven requested changes

2021-08-24 15:54 UTC, diraven commented on events_library/management/commands/event_handler.py
> +                if sync_task_serializer.is_valid():
Don't see an exception though. Where is it?

2021-08-25 11:24 UTC, waseem-uddin commented on events_library/management/commands/event_handler.py
> +                if sync_task_serializer.is_valid():
Whoops! Somehow it got erased. Fixed now.

2021-08-28 16:57 UTC, merged