feat: translations serializer mixin
selfdecode/events-library pull request #35
Opened 2021-12-16 13:50 UTC by christopherhuber

## Context
https://selfdecode.slack.com/archives/G01DV1405U7/p1639588491225200

## Description
Defines a TranslationsSerializerMixin which adds the translations related fields to the serializer
Adds the mixin to GenericSerializer 

## PR Tasks
- [x] Tested locally or in a development environment.

2021-12-17 06:18 UTC, waseem-uddin commented on events_library/core/event_bus.py
>              """Serializer that extends ModelSerializer to support EnumFields"""
We might want to update the docstring too.

2021-12-17 06:18 UTC, waseem-uddin commented on events_library/core/event_bus_sns.py
>              """Serializer that extends ModelSerializer to support EnumFields"""
We might want to update the docstring too.

2021-12-17 06:39 UTC, royselfdecode commented
@christopherhuber ,
@waseem-uddin  and I discussed which events library version should we put this into.
As far as I understand only reports service will needs this events library update, right? The receiving end of the CUD events do not need this. Because we don't want to update the events library for every service.

2021-12-19 18:38 UTC, christopherhuber commented
> @christopherhuber , @waseem-uddin and I discussed which events library version should we put this into. As far as I understand only reports service will needs this events library update, right? The receiving end of the CUD events do not need this. Because we don't want to update the events library for every service.

That is correct - the receiving end just aggregates all other fields in data so there should be no issue

2021-12-21 07:43 UTC, waseem-uddin approved these changes

2021-12-21 07:50 UTC, diraven requested changes

2021-12-21 07:50 UTC, diraven commented on events_library/domain/utils.py
> +        except AttributeError:
AttributeError is pretty common exception. Such clause will silence any of those, not just those that have to deal with translations potentially leading to very subtle and hard to debug issues. E.g. if deprecation happens between django versions and one of the attributes is removed - we will have no way to know why suddenly we stopped processing translations.

"It's easier to ask for forgiveness then for permission" doesn't quite work here for that reason. Here we may want to ask for permission instead since we can be more specific here.

I assume the intent is to raise AttributeError if model.translations attribute does not exist. Instead, we could either compare model type or check if translations attribute is present. We still want AttributeError to be raised for the rest of the code if there is an issue.

2021-12-21 17:48 UTC, diraven approved these changes

2021-12-21 18:02 UTC, merged